
title: Surgical AI research group
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Website of the Surgical AI Lab
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: surgerai
github_username: surgical-ai-lab

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
include: ['_pages', '_posts']

header_pages:
  - _pages/people.markdown
  - _pages/publications.markdown
  - _pages/projects.markdown
