# Welcome to the Surgical AI Lab Website Configuration!
#
# This config file contains settings that personalize your lab website. Customize
# these settings to reflect the focus and goals of your lab.

# Site settings
# These settings personalize your lab website. You can access them in the templates
# via {{ site.title }}, {{ site.description }}, etc.

title: Surgical AI Research Group
description: >-
  Welcome to the official website of the Surgical AI Lab. Explore our research
  projects, publications, resources, and team members.
baseurl: "" # Set this if your site is hosted in a subdirectory, e.g., /blog
url: "" # Set your base hostname & protocol, e.g., http://example.com
twitter_username: surgical_ai
github_username: surgical-ai-lab

# Build settings
# These settings define the build configuration for your site.

theme: jekyll-theme-cayman # Set your preferred theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# These items will not be processed by default but can be included explicitly.
exclude:
  - Gemfile
  - Gemfile.lock
include: ['_pages', '_posts']

# Header pages
# These pages will be displayed in the site header/navigation.
header_pages:
  - _pages/people.markdown
  - _pages/publications.markdown
  - _pages/resources.markdown
  - _pages/projects.markdown
